### ISSUE TITLE
(not a bug) Quesion about your wiki

### ISSUE THREAD

**Issue by david-randoll** [DanielLiu1123/httpexchange-spring-boot-starter#31]
Love what you did with this. 

I am curious about how you generated your Wiki. I'm assuming from your README.md file some frontend library you used?

Thank you!

**Comment by DanielLiu1123** [comment]
[docsify](https://docsify.js.org/#/), easy and fun

**Comment by david-randoll** [comment]
> [docsify](https://docsify.js.org/#/), easy and fun
