### ISSUE TITLE
do not create a new HttpClient when it is not necessary

### ISSUE THREAD

**Issue by sjh836** [DanielLiu1123/httpexchange-spring-boot-starter#35]
In the buildRestClient method, HttpClient settings other than timeout are unintentionally initialized.

* I set RetryStrategy, evictIdleConnections, ObservationExecChainHandler etc in HttpClient.
* Read timeout was not set in yaml.
* This is because ClientHttpRequestFactories.get always creates a new HttpClient.

**Comment by DanielLiu1123** [comment]
Thank you very much for helping to identify these issues. I will try to address them, and if you're interested, you can also submit a PR to help improve this project.

**Comment by DanielLiu1123** [comment]
Fixed by #37

**Comment by sjh836** [comment]
Taking a Class as input and creating a ClientHttpRequestFactory instance with only read-timeout and connect-timeout is not scalable.

It would be better to inherit and change each channel config from ClientHttpRequestFactory, which reflects the user's settings.

I think we should be able to have multiple ClientHttpRequestFactory depending on the config.

For example, I'm using HttpComponentsClientHttpRequestFactory. I would like to register by implementing org.apache.hc.client5.http.impl.DefaultHttpRequestRetryStrategy, but there is currently no way to expand it.

**Comment by sjh836** [comment]
I think the previous `@Bean` code is better.
As you explain in the documentation, it doesn't always apply globally.

Without changing the bean, extend it to a concept similar to `.mutate().timeout().build()`
and use it in `getRequestFactory(HttpExchangeProperties.Channel channelConfig)`

**Comment by sjh836** [comment]
This change makes `beanFactory.getBeanProvider(RestClient.Builder.class)` ineffective.

**Comment by DanielLiu1123** [comment]
Spring provides `RestClientCustomizer` and `RestTemplateCustomizer`, which we can use to configure the requestFactory. Compared to directly handling the `ClientHttpRequestFactory` bean, this might be a better choice.

```java
// Customize ClientHttpRequestFactory for RestClient
@Bean
RestClientCustomizer restClientCustomizer() {
    return builder -> builder.requestFactory(new HttpComponentsClientHttpRequestFactory());
}

// Customize ClientHttpRequestFactory for RestTemplate
@Bean
RestTemplateCustomizer restTemplateCustomizer() {
    return restTemplate -> restTemplate.setRequestFactory(new HttpComponentsClientHttpRequestFactory());
}
```

See https://github.com/DanielLiu1123/httpexchange-spring-boot-starter/pull/46

**Comment by DanielLiu1123** [comment]
`3.2.4` introduces `HttpClientCustomizer`, you can use `Channel` configuration to customize the http client (RestClient, WebClient...).

```java

    @Bean
    HttpClientCustomizer.RestClientCustomizer restClientCustomizer() {
        return (RestClient.Builder client, HttpExchangeProperties.Channel channel) -> {
            if (Objects.equals(channel.getName(), "channel1")) {
                client.requestFactory(new JdkClientHttpRequestFactory());
            }
            if (Objects.equals(channel.getName(), "channel2")) {
                client.requestFactory(new HttpComponentsClientHttpRequestFactory());
            }
            if (Objects.equals(channel.getName(), "channel3")) {
                client.requestFactory(new SimpleClientHttpRequestFactory());
            }
        };
    }
```
